import { ArrowRight, BrainCircuit, FileOutput, Gauge, MapPin, ScanSearch, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import diabeticRetinopathyImage from '../../images/diabetic-retinopathy-causes-symptoms-treatments.jpg'
import ophthalmologistImage from '../../images/oftalmologo.webp'

const approach = [
  ['Image quality assessment', 'Check whether a retinal image is suitable for the next workflow step.', Gauge],
  ['Image enhancement', 'Support clearer review when enhancement is appropriate for the image.', Sparkles],
  ['AI analysis', 'Organize diabetic retinopathy assessment into a structured screening workflow.', ScanSearch],
  ['Explainable results', 'Present visual evidence such as heatmaps alongside an assessment.', BrainCircuit],
  ['Doctor and patient outputs', 'Prepare information for different readers without replacing clinical judgment.', FileOutput],
]

function About() {
  return (
    <div className="overflow-hidden bg-[#F7FAFA] text-[#263B4D]">
      <section className="bg-white px-5 py-16 sm:px-8 sm:py-24 lg:py-28"><div className="mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-[1fr_0.9fr] lg:gap-20"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#0F8F87]">About Netrika</p><h1 className="font-heading mt-5 text-5xl font-semibold leading-[1.08] tracking-[-0.045em] sm:text-6xl">Making retinal screening clearer and more accessible.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#617589]">Netrika is an AI-powered, explainable diabetic retinopathy screening platform designed to support faster and more accessible retinal screening.</p></div><figure className="overflow-hidden rounded-2xl border border-[#D6E8E6] bg-[#F7FAFA] shadow-[0_12px_36px_rgba(7,21,47,0.08)]"><img src={ophthalmologistImage} alt="Ophthalmologist examining a patient" className="aspect-[4/3] w-full object-cover" /><figcaption className="px-5 py-4 text-xs leading-5 text-[#617589]">Designed around the practical context of retinal screening.</figcaption></figure></div></section>
      <section className="px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:gap-20"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#0F8F87]">The problem</p><h2 className="font-heading mt-4 text-3xl font-semibold sm:text-4xl">Screening needs clarity at every step.</h2></div><div className="space-y-5 text-base leading-7 text-[#617589]"><p>Diabetic retinopathy can threaten vision when it is not detected and referred appropriately.</p><p>In resource-constrained settings, screening workflows can be difficult to operate consistently. Retinal image quality can vary, and conventional AI systems can be difficult for clinicians to interpret.</p><p>Netrika brings a guided, quality-aware process together with evidence that helps healthcare workers understand an assessment.</p></div><figure className="overflow-hidden rounded-xl border border-[#D6E8E6] bg-white shadow-[0_8px_24px_rgba(7,21,47,0.04)] lg:col-start-2"><img src={diabeticRetinopathyImage} alt="Educational diabetic retinopathy illustration" className="w-full object-cover" /><figcaption className="px-5 py-4 text-xs text-[#617589]">Educational context, not a diagnostic result.</figcaption></figure></div></section>
      <section className="bg-white px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-6xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#0F8F87]">Our approach</p><h2 className="font-heading mt-4 max-w-2xl text-3xl font-semibold sm:text-4xl">A workflow built around useful decisions.</h2><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{approach.map(([title, description, Icon]) => <article key={title} className="rounded-xl border border-[#D6E8E6] bg-white p-6 shadow-[0_8px_30px_rgba(7,21,47,0.04)]"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-[#E7F5F3] text-[#0F8F87]"><Icon aria-hidden="true" size={21} /></div><h3 className="font-heading mt-6 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#617589]">{description}</p></article>)}</div><p className="mt-6 text-xs text-[#617589]">Prototype note: model-connected services will be connected in future implementation stages.</p></div></section>
      <section className="bg-[#07152F] px-5 py-20 text-white sm:px-8 lg:py-24"><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[1fr_0.8fr] lg:gap-20"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#0F8F87]">Built for India</p><h2 className="font-heading mt-4 text-3xl font-semibold sm:text-4xl">A practical foundation for care where it begins.</h2><p className="mt-5 text-base leading-7 text-[#D6E8E6]">Netrika is being shaped for primary health centres, screening camps, and resource-constrained healthcare settings.</p></div><div className="rounded-xl border border-[#243B61] p-7"><MapPin aria-hidden="true" className="text-[#0F8F87]" size={28} /><p className="mt-5 text-lg font-semibold">Accessible by design</p><p className="mt-3 text-sm leading-6 text-[#D6E8E6]">Clear workflows, local context, and future English and Hindi support.</p></div></div></section>
      <section className="px-5 py-20 sm:px-8 lg:py-24"><div className="mx-auto flex max-w-4xl flex-col items-center rounded-2xl bg-[#E7F5F3] px-6 py-14 text-center sm:px-10"><h2 className="font-heading text-3xl font-semibold sm:text-4xl">Begin with a clearer screening workflow.</h2><p className="mt-4 text-base text-[#617589]">Explore the current Netrika frontend prototype.</p><Link to="/login" className="mt-8 inline-flex items-center gap-2 rounded-md bg-[#0F8F87] px-5 py-3 text-sm font-semibold text-white hover:bg-[#08746E]">Start Screening <ArrowRight aria-hidden="true" size={17} /></Link></div></section>
    </div>
  )
}

export default About